"""
Causal Broker Attribution & Smart Money Watchlist Generator.
Links historical broker accumulation/distribution holding patterns to subsequent 
forward price returns, and automatically generates high-conviction probable 
accumulation watchlists.
"""

from __future__ import annotations

import pandas as pd
import numpy as np
from src.ml.broker_alpha import analyze_broker_accumulation
from src.watchlist import add_symbol
from src.screener import _is_excluded
from src.ml.predictor import predict_breakout_prob

def analyze_causal_broker_returns(conn) -> pd.DataFrame:
    """
    Correlates historical broker net accumulation patterns with forward T+5 and T+20 returns.
    """
    query = """
    SELECT 
        h.symbol,
        h.broker_id,
        h.signal,
        h.net_22d,
        h.net_66d,
        h.margin_pct,
        100.0 * (f_5.close_price / m.close_price - 1) AS fwd_t5_ret,
        100.0 * (f_20.close_price / m.close_price - 1) AS fwd_t20_ret
    FROM screener_signals_history h
    JOIN daily_market_summary m ON h.symbol = m.symbol AND h.trade_date = m.trade_date
    LEFT JOIN LATERAL (
        SELECT close_price FROM daily_market_summary 
        WHERE symbol = h.symbol AND trade_date > h.trade_date 
        ORDER BY trade_date ASC LIMIT 1 OFFSET 4
    ) f_5 ON TRUE
    LEFT JOIN LATERAL (
        SELECT close_price FROM daily_market_summary 
        WHERE symbol = h.symbol AND trade_date > h.trade_date 
        ORDER BY trade_date ASC LIMIT 1 OFFSET 19
    ) f_20 ON TRUE
    """
    print("Running causal broker attribution query...")
    df = pd.read_sql(query, conn)
    if df.empty:
        return df

    return df

def generate_probable_accumulation_watchlist(conn, min_net_qty: int = 15000) -> list[str]:
    """
    Scans current broker rollups and market metrics to identify probable accumulation 
    stocks and automatically populates the user research watchlist.
    """
    df = analyze_broker_accumulation(conn, min_net_qty=min_net_qty)
    if df.empty:
        return []

    # Filter for Stealth Accumulation patterns with positive unrealized margin
    stealth = df[(df['broker_pattern'] == 'STEALTH_ACCUMULATION') & (df['unrealized_margin_pct'] >= 0)]
    if stealth.empty:
        return []

    # Group by symbol to find top accumulators
    candidates = stealth.groupby('symbol').agg(
        total_accumulated=('net_66d', 'sum'),
        avg_margin=('unrealized_margin_pct', 'mean'),
        lead_broker=('broker_id', 'first'),
        current_price=('current_price', 'last')
    ).reset_index()
    candidates = candidates[~candidates['symbol'].apply(_is_excluded)]
    candidates = candidates.sort_values(by='total_accumulated', ascending=False)

    added_symbols = []
    for _, row in candidates.head(10).iterrows():
        sym = row['symbol']
        broker_id = int(row['lead_broker'])
        qty = int(row['total_accumulated'])
        margin = float(row['avg_margin'])
        
        thesis = (
            f"Probable Accumulation: Broker #{broker_id} accumulated {qty:,} shares "
            f"over 66 sessions. Unrealized margin: +{margin:.1f}%. "
            f"Smart money stealth building signature detected."
        )
        tags = "SMART_MONEY,ACCUMULATION,BROKER_ALPHA"
        
        try:
            add_symbol(conn, symbol=sym, thesis=thesis, tags=tags, note=f"Auto-generated by Broker Alpha Engine. Lead Broker: #{broker_id}")
            added_symbols.append(sym)
            print(f"Added {sym} to watchlist (Lead Broker: #{broker_id}, Accumulated: {qty:,})")
        except Exception as e:
            print(f"Error adding {sym}: {e}")

    return added_symbols

if __name__ == "__main__":
    from src.db import get_conn
    conn = get_conn()
    try:
        print("--- CAUSAL BROKER ATTRIBUTION SUMMARY ---")
        res = analyze_causal_broker_returns(conn)
        if not res.empty:
            summary = res.groupby('signal').agg(
                signals_count=('symbol', 'count'),
                avg_t5_return=('fwd_t5_ret', 'mean'),
                avg_t20_return=('fwd_t20_ret', 'mean')
            ).reset_index()
            print(summary.to_string(index=False))
        
        print("\n--- GENERATING PROBABLE ACCUMULATION WATCHLIST ---")
        added = generate_probable_accumulation_watchlist(conn)
        print(f"Successfully added {len(added)} stocks to watchlist: {added}")
    finally:
        conn.close()
